
SELECT 
    *
FROM
    `datastage`.`stg_servidores`;

CREATE TABLE cadastro_servidores LIKE stg_servidores;

ALTER TABLE cadastro_servidores 
DROP COLUMN SIGLA_FUNCAO,
DROP COLUMN NIVEL_FUNCAO,
DROP COLUMN FUNCAO,
DROP COLUMN UORG_EXERCICIO,
DROP COLUMN DATA_INICIO_AFASTAMENTO,
DROP COLUMN DATA_TERMINO_AFASTAMENTO,
DROP COLUMN DATA_INGRESSO_CARGOFUNCAO,
DROP COLUMN DATA_NOMEACAO_CARGOFUNCAO,
DROP COLUMN DATA_INGRESSO_ORGAO,
DROP COLUMN MES,
DROP COLUMN ANO
;

ALTER TABLE cadastro_servidores ADD COLUMN id INT AUTO_INCREMENT UNIQUE FIRST;

ALTER TABLE `datastage`.`cadastro_servidores` 
ADD INDEX `nome_servidor` (`NOME`(100) ASC) VISIBLE,
ADD INDEX `cpf` (`CPF`(15) ASC) VISIBLE,
ADD UNIQUE INDEX `serv` (`Id_SERVIDOR_PORTAL` ASC, `NOME`(100) ASC, `CPF`(15) ASC, `MATRICULA`(10) ASC) INVISIBLE
;

INSERT IGNORE INTO cadastro_servidores
(
	Id_SERVIDOR_PORTAL,
	NOME,
	CPF,
	MATRICULA
)
SELECT DISTINCT 
	Id_SERVIDOR_PORTAL,
	NOME,
	CPF,
	MATRICULA
FROM  stg_servidores
;

CREATE TABLE cargo_servidores LIKE stg_servidores;

ALTER TABLE cargo_servidores 
DROP COLUMN NOME,
DROP COLUMN CPF,
DROP COLUMN MATRICULA

;

ALTER TABLE cargo_servidores ADD COLUMN id INT AUTO_INCREMENT UNIQUE FIRST;
ALTER TABLE cargo_servidores ADD COLUMN FK_SERVIDOR INT ;

ALTER TABLE `datastage`.`cargo_servidores` 
ADD PRIMARY KEY (`id`);
ALTER TABLE `datastage`.`cargo_servidores` 
ADD INDEX `sigla` (`SIGLA_FUNCAO`(10) ASC) VISIBLE,
ADD INDEX `funcao` (`NIVEL_FUNCAO`(5) ASC) VISIBLE;

ALTER TABLE `datastage`.`cargo_servidores` 
ADD INDEX `uni` (`SIGLA_FUNCAO` ASC, `NIVEL_FUNCAO` ASC, `FUNCAO` ASC, `UORG_EXERCICIO` ASC, `DATA_INICIO_AFASTAMENTO` ASC, `DATA_TERMINO_AFASTAMENTO` ASC, `DATA_INGRESSO_CARGOFUNCAO` ASC, `DATA_NOMEACAO_CARGOFUNCAO` ASC, `DATA_INGRESSO_ORGAO` ASC, `ANO` ASC, `MES` ASC, `FK_SERVIDOR` ASC) VISIBLE;
ALTER TABLE `datastage`.`cargo_servidores` ALTER INDEX `id` INVISIBLE;

