
SHOW CREATE TABLE cargo_servidores;

CREATE TABLE `tbl_cargo_servidores` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `SIGLA_FUNCAO` text,
   `NIVEL_FUNCAO` text,
   `FUNCAO` text,
   `UORG_EXERCICIO` text,
   `DATA_INICIO_AFASTAMENTO` date DEFAULT NULL,
   `DATA_TERMINO_AFASTAMENTO` date DEFAULT NULL,
   `DATA_INGRESSO_CARGOFUNCAO` date DEFAULT NULL,
   `FK_SERVIDOR` int(11) DEFAULT NULL,
   `UF_EXERCICIO` varchar(100) DEFAULT NULL,
   `MES` int(2) DEFAULT NULL,
   `ANO` int(4) DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `cargo_unik` (`SIGLA_FUNCAO`(10),`NIVEL_FUNCAO`(10),`FUNCAO`(10),`UORG_EXERCICIO`(100),`DATA_INICIO_AFASTAMENTO`,`DATA_TERMINO_AFASTAMENTO`,`DATA_INGRESSO_CARGOFUNCAO`,`ANO`,`MES`,`FK_SERVIDOR`,`UF_EXERCICIO`(5)),
   KEY `sigla` (`SIGLA_FUNCAO`(10)),
   KEY `funcao` (`NIVEL_FUNCAO`(5)),
   KEY `fk_cas_ser` (`FK_SERVIDOR`),
   KEY `ano_mes` (`ANO`),
   KEY `mes` (`MES`),
   CONSTRAINT `fk_cadastro_ser` FOREIGN KEY (`FK_SERVIDOR`) REFERENCES `cadastro_servidores` (`id`)
 ) ENGINE=InnoDB AUTO_INCREMENT=20606513 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci